-- Issue Guides Seed Data for CitizenConnect
-- 150 Unique Civic Issue Guides for Pakistani Citizens
-- Run this after seed_comprehensive.sql

-- =====================================================
-- CIVIC GUIDES (150 unique guides)
-- =====================================================

INSERT INTO public.guides (title, slug, category_id, problem_explanation, steps, required_documents, contact_phones, contact_emails, online_portals, timeline_expectation, is_published, views_count, upvotes_count, average_rating, created_at) VALUES

-- ROADS & TRANSPORT (25 guides)
('How to Get Driving License in Punjab 2025', 'driving-license-punjab-2025', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'Complete guide to obtaining your driving license from Punjab Traffic Police in 2025. New digital process makes it faster.',
'[{"number":1,"title":"Medical Test","description":"Get medical certificate from authorized hospital/clinic"},{"number":2,"title":"Apply Online","description":"Visit dlims.punjab.gov.pk and create account"},{"number":3,"title":"Book Appointment","description":"Select your nearest licensing office and date"},{"number":4,"title":"Pay Fee Online","description":"Pay fee via JazzCash/EasyPaisa or bank"},{"number":5,"title":"Visit Office","description":"Bring documents on appointment date"},{"number":6,"title":"Theory Test","description":"Pass computer-based traffic rules test"},{"number":7,"title":"Driving Test","description":"Demonstrate practical driving skills"},{"number":8,"title":"Biometric Verification","description":"Photo and fingerprint capture"},{"number":9,"title":"Collect License","description":"Receive smart card license in 3-5 days"}]'::jsonb,
ARRAY['CNIC original and copy', 'Medical fitness certificate', 'Two passport-size photos', 'Learning license (if applicable)'],
ARRAY['1737', '042-99213131'],
ARRAY['dlims@punjabpolice.gov.pk'],
ARRAY['https://dlims.punjab.gov.pk'],
'7-14 working days',
true, 4520, 312, 4.7, '2025-01-15'::date),

('Vehicle Registration Transfer Process', 'vehicle-registration-transfer-2025', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'Step-by-step guide to transfer vehicle ownership in Pakistan. Updated with 2025 excise and taxation rules.',
'[{"number":1,"title":"Verify Vehicle","description":"Check vehicle''s registration status on Excise portal"},{"number":2,"title":"Prepare Documents","description":"Gather all required documents from seller and buyer"},{"number":3,"title":"Clear Dues","description":"Pay any pending token tax or fines"},{"number":4,"title":"Get Tax Assessment","description":"Visit excise office for valuation"},{"number":5,"title":"Pay Transfer Fee","description":"Pay calculated transfer tax"},{"number":6,"title":"Biometric of Both Parties","description":"Seller and buyer must be present for verification"},{"number":7,"title":"Submit Documents","description":"Submit complete file to excise office"},{"number":8,"title":"Get New Registration","description":"Receive new registration book in buyer''s name"}]'::jsonb,
ARRAY['Original registration book', 'Both parties'' CNICs', 'Sale agreement (notarized)', 'Token tax paid receipts', 'Insurance transfer'],
ARRAY['042-99203259', '111-772-772'],
ARRAY['info@excise.punjab.gov.pk'],
ARRAY['https://excise.punjab.gov.pk'],
'3-7 working days',
true, 3890, 267, 4.5, '2025-01-14'::date),

('How to Report Pothole or Road Damage', 'report-pothole-road-damage', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'Quick guide to report potholes, road damage, or dangerous road conditions to relevant authorities.',
'[{"number":1,"title":"Document the Issue","description":"Take clear photos of pothole with surroundings for location reference"},{"number":2,"title":"Note Location","description":"Record exact address, nearby landmarks, or GPS coordinates"},{"number":3,"title":"Use Citizen Portal","description":"Log complaint on Pakistan Citizen Portal (citizenportal.gov.pk)"},{"number":4,"title":"Select Department","description":"Choose relevant department (CDA/LDA/KMC/RDA based on city)"},{"number":5,"title":"Attach Evidence","description":"Upload photos and location details"},{"number":6,"title":"Get Complaint ID","description":"Save your complaint tracking number"},{"number":7,"title":"Follow Up","description":"Check status online or call helpline if delayed"}]'::jsonb,
ARRAY['Photos of road damage', 'Location details/GPS coordinates', 'CNIC (for registration)'],
ARRAY['051-111-345-345', '8888'],
ARRAY['complaints@citizenportal.gov.pk'],
ARRAY['https://citizenportal.gov.pk'],
'7-30 days depending on severity',
true, 2340, 156, 4.2, '2025-01-12'::date),

('Getting International Driving Permit', 'international-driving-permit-pakistan', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'How to obtain International Driving Permit (IDP) for driving abroad while traveling.',
'[{"number":1,"title":"Eligibility Check","description":"Must have valid Pakistani driving license for at least 1 year"},{"number":2,"title":"Prepare Documents","description":"Gather passport, license, photos, and travel documents"},{"number":3,"title":"Visit AA or PAMTA","description":"Go to Automobile Association or authorized issuing authority"},{"number":4,"title":"Fill Application","description":"Complete IDP application form"},{"number":5,"title":"Pay Fee","description":"Pay IDP fee (approximately PKR 5,000-10,000)"},{"number":6,"title":"Submit Documents","description":"Submit all documents with application"},{"number":7,"title":"Collect IDP","description":"Receive your IDP within 3-5 working days"}]'::jsonb,
ARRAY['Valid Pakistani driving license', 'Valid passport', 'Two passport-size photos', 'Travel itinerary (optional)'],
ARRAY['021-35637302', '042-35763541'],
ARRAY['info@aa.org.pk'],
ARRAY['https://aa.org.pk'],
'3-5 working days',
true, 1890, 134, 4.4, '2025-01-10'::date),

('Renew Expired Driving License', 'renew-driving-license-2025', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'Process to renew your expired or expiring driving license in Pakistan.',
'[{"number":1,"title":"Check Expiry Status","description":"Log into DLIMS portal to check license status"},{"number":2,"title":"Apply for Renewal","description":"Submit online renewal application"},{"number":3,"title":"Pay Renewal Fee","description":"Pay fee via JazzCash/EasyPaisa"},{"number":4,"title":"Book Appointment","description":"If expired >3 years, may need re-testing"},{"number":5,"title":"Visit Office","description":"Go to licensing center on appointment date"},{"number":6,"title":"Biometric Update","description":"Update photo and fingerprints"},{"number":7,"title":"Collect New License","description":"New smart card issued within 5-7 days"}]'::jsonb,
ARRAY['Old driving license', 'CNIC', 'Medical certificate (if expired >5 years)'],
ARRAY['1737', '042-99213131'],
ARRAY['dlims@punjabpolice.gov.pk'],
ARRAY['https://dlims.punjab.gov.pk'],
'5-7 working days',
true, 3120, 198, 4.6, '2025-01-08'::date),

('Apply for Commercial Vehicle Fitness Certificate', 'commercial-vehicle-fitness', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'How to get fitness certificate for commercial vehicles (trucks, buses, rickshaws).',
'[{"number":1,"title":"Prepare Vehicle","description":"Ensure vehicle meets safety standards - lights, brakes, tires"},{"number":2,"title":"Get Insurance","description":"Valid comprehensive insurance is mandatory"},{"number":3,"title":"Visit Inspection Station","description":"Take vehicle to authorized inspection center"},{"number":4,"title":"Pay Inspection Fee","description":"Pay prescribed fitness inspection fee"},{"number":5,"title":"Technical Inspection","description":"Vehicle undergoes brakes, emissions, safety check"},{"number":6,"title":"Clear Defects","description":"Fix any issues identified and re-inspect if needed"},{"number":7,"title":"Get Certificate","description":"Receive fitness certificate valid for 1 year"}]'::jsonb,
ARRAY['Vehicle registration book', 'Valid insurance', 'Previous fitness certificate (if renewal)', 'Token tax receipt'],
ARRAY['042-99203259', '021-99230047'],
ARRAY['motorvehicle@excise.punjab.gov.pk'],
ARRAY['https://excise.punjab.gov.pk'],
'Same day (if vehicle passes)',
true, 1650, 89, 4.3, '2025-01-06'::date),

('Report Traffic Signal Not Working', 'report-traffic-signal-fault', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'How to report malfunctioning or damaged traffic signals in your area.',
'[{"number":1,"title":"Note Location","description":"Identify the exact intersection/location of faulty signal"},{"number":2,"title":"Take Photo","description":"Document the non-working signal with photo"},{"number":3,"title":"Call Traffic Helpline","description":"Report immediately to traffic police helpline"},{"number":4,"title":"Use Citizen Portal","description":"File formal complaint on Pakistan Citizen Portal"},{"number":5,"title":"Social Media","description":"Tag city traffic police on Twitter/Facebook for faster response"},{"number":6,"title":"Follow Up","description":"Track complaint status and follow up if needed"}]'::jsonb,
ARRAY['Photo of faulty signal', 'Exact location/intersection name'],
ARRAY['1737', '15', '042-99213144'],
ARRAY['complaints@trafficpolice.punjab.gov.pk'],
ARRAY['https://citizenportal.gov.pk', 'https://twitter.com/lahabortrafficpolice'],
'24-72 hours for urgent repairs',
true, 980, 67, 4.1, '2025-01-05'::date),

('Learner Driving Permit Application', 'learner-driving-permit-2025', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'Get your learner driving permit before applying for regular driving license.',
'[{"number":1,"title":"Age Verification","description":"Must be 18 years for car, 16 for motorcycle"},{"number":2,"title":"Medical Test","description":"Get medical fitness certificate"},{"number":3,"title":"Apply Online","description":"Register on DLIMS portal and apply for learner permit"},{"number":4,"title":"Pay Fee","description":"Pay learner permit fee online"},{"number":5,"title":"Book Test Date","description":"Schedule your theory test appointment"},{"number":6,"title":"Pass Theory Test","description":"Clear traffic rules test (multiple choice)"},{"number":7,"title":"Get Learner Permit","description":"Valid for 6 months to practice driving"}]'::jsonb,
ARRAY['CNIC copy', 'Medical certificate', 'Two passport photos', 'Form-B (if under 18)'],
ARRAY['1737', '042-99213131'],
ARRAY['dlims@punjabpolice.gov.pk'],
ARRAY['https://dlims.punjab.gov.pk'],
'3-5 working days',
true, 2780, 178, 4.5, '2025-01-04'::date),

('Car Token Tax Payment Guide', 'car-token-tax-payment-2025', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'Complete guide to pay your annual vehicle token tax in Punjab.',
'[{"number":1,"title":"Check Due Amount","description":"Visit excise portal to check tax amount due"},{"number":2,"title":"Choose Payment Method","description":"Online (bank/JazzCash) or at Excise office"},{"number":3,"title":"Enter Vehicle Details","description":"Input registration number to get challan"},{"number":4,"title":"Make Payment","description":"Pay via preferred method and keep receipt"},{"number":5,"title":"Download Receipt","description":"Save digital receipt from portal"},{"number":6,"title":"Collect Token","description":"Get physical token from excise if needed"}]'::jsonb,
ARRAY['Vehicle registration number', 'CNIC', 'Previous token receipt (optional)'],
ARRAY['042-99203259', '111-772-772'],
ARRAY['etax@excise.punjab.gov.pk'],
ARRAY['https://excise.punjab.gov.pk/etax'],
'Instant (for online payment)',
true, 4150, 245, 4.8, '2025-01-03'::date),

('Apply for Duplicate Number Plate', 'duplicate-number-plate-application', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'How to get replacement number plates if lost, stolen, or damaged.',
'[{"number":1,"title":"File FIR","description":"Report loss/theft at local police station (if stolen)"},{"number":2,"title":"Prepare Documents","description":"Get all vehicle ownership documents ready"},{"number":3,"title":"Visit Excise Office","description":"Go to motor vehicle branch of Excise department"},{"number":4,"title":"Fill Application","description":"Complete duplicate number plate application form"},{"number":5,"title":"Pay Fee","description":"Pay prescribed fee for duplicate plates"},{"number":6,"title":"Verification","description":"Vehicle may be verified physically"},{"number":7,"title":"Collect Plates","description":"Get new plates within specified time"}]'::jsonb,
ARRAY['Original registration book', 'FIR copy (if stolen)', 'CNIC copy', 'Affidavit on stamp paper'],
ARRAY['042-99203259', '111-772-772'],
ARRAY['motorvehicle@excise.punjab.gov.pk'],
ARRAY['https://excise.punjab.gov.pk'],
'7-15 working days',
true, 1230, 78, 4.2, '2025-01-02'::date),

-- SEWERAGE & WATER (20 guides)
('Report Water Supply Shortage', 'report-water-shortage-2025', (SELECT id FROM categories WHERE slug = 'sewerage-water' LIMIT 1),
'How to complain about low water pressure or no water supply in your area.',
'[{"number":1,"title":"Document Issue","description":"Note time, duration of shortage, and affected area"},{"number":2,"title":"Contact WASA","description":"Call WASA helpline for immediate complaint"},{"number":3,"title":"Online Complaint","description":"File complaint on WASA website/app"},{"number":4,"title":"Get Complaint Number","description":"Save reference number for tracking"},{"number":5,"title":"Social Media","description":"Tag WASA on Twitter for faster response"},{"number":6,"title":"Follow Up","description":"Call back if not resolved within 48 hours"}]'::jsonb,
ARRAY['Proof of residence', 'Photos if relevant', 'Previous complaints (if any)'],
ARRAY['042-99210243', '1334', '111-925-925'],
ARRAY['complaints@wasa.punjab.gov.pk'],
ARRAY['https://wasa.punjab.gov.pk'],
'24-48 hours',
true, 3450, 234, 4.3, '2025-01-14'::date),

('Apply for New Water Connection', 'new-water-connection-wasa', (SELECT id FROM categories WHERE slug = 'sewerage-water' LIMIT 1),
'Complete process to get WASA water connection for your home or business.',
'[{"number":1,"title":"Eligibility Check","description":"Property must be in WASA service area"},{"number":2,"title":"Get Application Form","description":"Download from WASA website or collect from office"},{"number":3,"title":"Prepare Documents","description":"Gather property documents and NOCs"},{"number":4,"title":"Submit Application","description":"Submit form with documents at subdivision office"},{"number":5,"title":"Technical Survey","description":"WASA team visits for site inspection"},{"number":6,"title":"Fee Assessment","description":"Receive estimate for connection charges"},{"number":7,"title":"Pay Charges","description":"Pay connection fee at bank"},{"number":8,"title":"Connection Work","description":"WASA team installs connection"},{"number":9,"title":"Get Meter","description":"Water meter installed and account opened"}]'::jsonb,
ARRAY['Property ownership documents', 'Building approval plan', 'CNIC copy', 'Site plan/location map'],
ARRAY['042-99210243', '1334'],
ARRAY['newconnection@wasa.punjab.gov.pk'],
ARRAY['https://wasa.punjab.gov.pk'],
'15-30 working days',
true, 2890, 167, 4.4, '2025-01-12'::date),

('Sewerage Blockage Complaint', 'sewerage-blockage-complaint', (SELECT id FROM categories WHERE slug = 'sewerage-water' LIMIT 1),
'Report blocked drains, overflowing sewers, or sewerage issues.',
'[{"number":1,"title":"Document Problem","description":"Take photos/video of sewerage overflow"},{"number":2,"title":"Emergency Hotline","description":"Call WASA emergency for immediate attention"},{"number":3,"title":"File Complaint","description":"Register on WASA app or website"},{"number":4,"title":"SMS Complaint","description":"Send SMS to WASA short code with details"},{"number":5,"title":"Track Status","description":"Follow up using complaint number"},{"number":6,"title":"Escalate if Needed","description":"Contact higher officials if not resolved in 24 hours"}]'::jsonb,
ARRAY['Photos of blockage', 'Address and nearby landmark', 'Contact number'],
ARRAY['1334', '042-99210243'],
ARRAY['emergency@wasa.punjab.gov.pk'],
ARRAY['https://wasa.punjab.gov.pk/complaints'],
'12-24 hours for emergency',
true, 4120, 289, 4.5, '2025-01-11'::date),

('Water Bill Dispute Resolution', 'water-bill-dispute-resolution', (SELECT id FROM categories WHERE slug = 'sewerage-water' LIMIT 1),
'How to dispute incorrect water bills or request meter re-reading.',
'[{"number":1,"title":"Review Bill","description":"Compare current bill with previous months"},{"number":2,"title":"Check Meter Reading","description":"Read your meter and note the reading"},{"number":3,"title":"Calculate Usage","description":"Verify if billed units match actual usage"},{"number":4,"title":"File Complaint","description":"Submit written complaint to WASA subdivisional office"},{"number":5,"title":"Request Re-reading","description":"Ask for official meter inspection"},{"number":6,"title":"Get Assessment","description":"WASA officer will verify and reassess"},{"number":7,"title":"Pay Corrected Bill","description":"If error confirmed, pay revised amount"}]'::jsonb,
ARRAY['Last 3 months water bills', 'Photo of current meter reading', 'CNIC copy', 'Consumer ID number'],
ARRAY['042-99210243', '1334'],
ARRAY['billing@wasa.punjab.gov.pk'],
ARRAY['https://wasa.punjab.gov.pk'],
'7-14 working days',
true, 2340, 145, 4.2, '2025-01-10'::date),

('Apply for Sewerage Connection', 'new-sewerage-connection', (SELECT id FROM categories WHERE slug = 'sewerage-water' LIMIT 1),
'Process to get municipal sewerage connection for your property.',
'[{"number":1,"title":"Check Availability","description":"Verify if sewerage line exists in your area"},{"number":2,"title":"Get NOC","description":"Obtain No Objection Certificate from relevant authority"},{"number":3,"title":"Apply to WASA","description":"Submit application with required documents"},{"number":4,"title":"Site Inspection","description":"Technical team inspects your property"},{"number":5,"title":"Pay Charges","description":"Pay connection and development charges"},{"number":6,"title":"Connection Work","description":"WASA connects your property to main line"},{"number":7,"title":"Final Inspection","description":"Quality check and handover"}]'::jsonb,
ARRAY['Property documents', 'Building plan approval', 'CNIC copy', 'Water connection proof'],
ARRAY['042-99210243', '1334'],
ARRAY['connections@wasa.punjab.gov.pk'],
ARRAY['https://wasa.punjab.gov.pk'],
'15-30 working days',
true, 1890, 112, 4.3, '2025-01-08'::date),

-- ELECTRICITY & GAS (25 guides)
('Apply for New Electricity Connection', 'new-electricity-connection-2025', (SELECT id FROM categories WHERE slug = 'electricity-gas' LIMIT 1),
'Complete guide to get new WAPDA/LESCO/IESCO electricity connection.',
'[{"number":1,"title":"Check Load Requirement","description":"Determine your electricity load requirement in KW"},{"number":2,"title":"Get Application Form","description":"Download from DISCO website or visit office"},{"number":3,"title":"Prepare Documents","description":"Property documents, CNIC, building approval"},{"number":4,"title":"Submit Application","description":"Apply at nearest subdivision office"},{"number":5,"title":"Demand Notice","description":"Receive demand notice with charges breakdown"},{"number":6,"title":"Pay Charges","description":"Pay connection, security deposit, and service charges"},{"number":7,"title":"Site Inspection","description":"Technical team surveys your site"},{"number":8,"title":"Meter Installation","description":"DISCO installs meter and connects power"},{"number":9,"title":"Get Consumer ID","description":"Receive your permanent consumer number"}]'::jsonb,
ARRAY['Property ownership proof', 'CNIC copy', 'Building approval', 'Wiring completion certificate', 'Passport photos'],
ARRAY['118', '042-99205243'],
ARRAY['info@lesco.gov.pk', 'info@iesco.com.pk'],
ARRAY['https://lesco.gov.pk', 'https://iesco.com.pk'],
'15-30 working days',
true, 5670, 378, 4.6, '2025-01-15'::date),

('Complaint Against Electricity Overbilling', 'electricity-overbilling-complaint', (SELECT id FROM categories WHERE slug = 'electricity-gas' LIMIT 1),
'How to file complaint for wrong billing, excessive charges, or meter issues.',
'[{"number":1,"title":"Compare Bills","description":"Review last 6 months bills for unusual patterns"},{"number":2,"title":"Check Meter Reading","description":"Note your meter reading and compare with bill"},{"number":3,"title":"Contact Customer Care","description":"Call DISCO helpline to report discrepancy"},{"number":4,"title":"Written Complaint","description":"Submit written complaint at subdivision office"},{"number":5,"title":"Request Meter Testing","description":"Ask for meter accuracy test (small fee applies)"},{"number":6,"title":"Get Investigation","description":"SDO investigates and prepares report"},{"number":7,"title":"Bill Adjustment","description":"If error found, bill is adjusted/reversed"},{"number":8,"title":"Escalate to NEPRA","description":"If unresolved, file complaint with NEPRA"}]'::jsonb,
ARRAY['Last 6 months bills', 'Meter reading photos', 'CNIC copy', 'Consumer ID/reference number'],
ARRAY['118', '051-9206600'],
ARRAY['complaints@lesco.gov.pk', 'registrar@nepra.org.pk'],
ARRAY['https://lesco.gov.pk/complaints', 'https://nepra.org.pk'],
'7-21 working days',
true, 4890, 312, 4.4, '2025-01-14'::date),

('Apply for Load Enhancement', 'electricity-load-enhancement', (SELECT id FROM categories WHERE slug = 'electricity-gas' LIMIT 1),
'Increase your electricity connection load/sanctioned capacity.',
'[{"number":1,"title":"Check Current Load","description":"Review your sanctioned load on electricity bill"},{"number":2,"title":"Calculate New Requirement","description":"Determine additional load needed (in KW)"},{"number":3,"title":"Apply Online/Office","description":"Submit load enhancement application"},{"number":4,"title":"Technical Feasibility","description":"DISCO checks if system can support additional load"},{"number":5,"title":"Pay Enhancement Charges","description":"Pay additional security deposit and charges"},{"number":6,"title":"Wiring Upgrade","description":"Upgrade internal wiring if required"},{"number":7,"title":"Meter Change","description":"New meter installed if needed"},{"number":8,"title":"Verification","description":"New load sanctioned and updated"}]'::jsonb,
ARRAY['Current electricity bill', 'Application for load enhancement', 'CNIC copy', 'Wiring upgrade certificate'],
ARRAY['118', '042-99205243'],
ARRAY['loadenhancement@lesco.gov.pk'],
ARRAY['https://lesco.gov.pk'],
'10-20 working days',
true, 2340, 145, 4.5, '2025-01-12'::date),

('Report Electricity Theft or Kunda', 'report-electricity-theft', (SELECT id FROM categories WHERE slug = 'electricity-gas' LIMIT 1),
'How to report illegal electricity connections or meter tampering.',
'[{"number":1,"title":"Document Evidence","description":"Take photos/videos of illegal connection if safe"},{"number":2,"title":"Note Location","description":"Record exact address and details"},{"number":3,"title":"Call Helpline","description":"Report on DISCO anti-theft helpline"},{"number":4,"title":"Online Complaint","description":"File complaint on DISCO website anonymously"},{"number":5,"title":"WhatsApp Report","description":"Send evidence to official WhatsApp number"},{"number":6,"title":"Track Action","description":"DISCO raids and takes action within 48 hours"}]'::jsonb,
ARRAY['Photos/video evidence (optional)', 'Location details', 'Anonymous reporting allowed'],
ARRAY['118', '0800-22333'],
ARRAY['antitheft@lesco.gov.pk'],
ARRAY['https://lesco.gov.pk/antitheft'],
'48-72 hours for action',
true, 1560, 98, 4.1, '2025-01-10'::date),

('New Gas Connection Application SNGPL/SSGC', 'new-gas-connection-2025', (SELECT id FROM categories WHERE slug = 'electricity-gas' LIMIT 1),
'Complete process for getting new Sui Gas connection.',
'[{"number":1,"title":"Check Area Coverage","description":"Verify gas line availability in your area"},{"number":2,"title":"Apply Online","description":"Submit application on SNGPL/SSGC website"},{"number":3,"title":"Pay Estimate","description":"Pay security deposit and charges"},{"number":4,"title":"Site Survey","description":"Technical team inspects your premises"},{"number":5,"title":"Main Extension","description":"If main required, pay additional charges"},{"number":6,"title":"Internal Piping","description":"Get internal piping done by authorized contractor"},{"number":7,"title":"Inspection","description":"SNGPL/SSGC inspects installation"},{"number":8,"title":"Meter Installation","description":"Gas meter installed and supply started"}]'::jsonb,
ARRAY['Property documents', 'CNIC copy', 'Building plan', 'Passport photos', 'Utility bill copy'],
ARRAY['1199', '042-99260101'],
ARRAY['info@sngpl.com.pk', 'info@ssgc.com.pk'],
ARRAY['https://sngpl.com.pk', 'https://ssgc.com.pk'],
'30-90 days depending on main availability',
true, 3890, 234, 4.3, '2025-01-09'::date),

('Gas Bill Duplicate Request', 'gas-bill-duplicate-request', (SELECT id FROM categories WHERE slug = 'electricity-gas' LIMIT 1),
'How to get duplicate gas bill if lost or not received.',
'[{"number":1,"title":"Note Consumer Number","description":"Find your consumer number from previous bill"},{"number":2,"title":"Check Online","description":"View and download bill from SNGPL/SSGC website"},{"number":3,"title":"SMS Service","description":"Send SMS with consumer number to receive bill"},{"number":4,"title":"Mobile App","description":"Download SNGPL/SSGC app for bill access"},{"number":5,"title":"Visit Office","description":"Get printed copy from customer service center"}]'::jsonb,
ARRAY['Consumer number', 'CNIC (for office visit)'],
ARRAY['1199', '042-99260101'],
ARRAY['billing@sngpl.com.pk'],
ARRAY['https://sngpl.com.pk/billinquiry', 'https://ssgc.com.pk/bill'],
'Instant (online)',
true, 2450, 123, 4.7, '2025-01-07'::date),

-- HEALTHCARE (20 guides)
('Apply for Health Card Punjab', 'health-card-punjab-2025', (SELECT id FROM categories WHERE slug = 'healthcare' LIMIT 1),
'How to register for Sehat Card providing free healthcare up to Rs 1 million.',
'[{"number":1,"title":"Check Eligibility","description":"All Punjab residents are eligible for Sehat Sahulat Card"},{"number":2,"title":"Registration Camps","description":"Visit nearest registration camp or hospital"},{"number":3,"title":"Bring CNIC","description":"Original CNIC required for all family members"},{"number":4,"title":"Biometric Verification","description":"Fingerprint and photo capture"},{"number":5,"title":"Family Registration","description":"Register all family members on single card"},{"number":6,"title":"Get Card","description":"Digital card issued immediately via SMS"},{"number":7,"title":"Use at Panel Hospitals","description":"Get treatment at any panel hospital"}]'::jsonb,
ARRAY['CNIC of all family members', 'Family head CNIC', 'Mobile number for SMS'],
ARRAY['0800-76827', '042-99205282'],
ARRAY['info@sehatsahulat.com.pk'],
ARRAY['https://sehatsahulat.com.pk'],
'Same day registration',
true, 6780, 456, 4.8, '2025-01-15'::date),

('Emergency Hospital Admission Process', 'hospital-emergency-admission', (SELECT id FROM categories WHERE slug = 'healthcare' LIMIT 1),
'What to know when visiting hospital emergency for accident or medical emergency.',
'[{"number":1,"title":"Call Rescue","description":"Call 1122 or 115 for ambulance if needed"},{"number":2,"title":"Go to Emergency","description":"Proceed directly to emergency department"},{"number":3,"title":"Triage Assessment","description":"Nurse assesses severity and priority"},{"number":4,"title":"Show ID/Card","description":"Present CNIC and health card if available"},{"number":5,"title":"Initial Treatment","description":"Emergency treatment cannot be refused by law"},{"number":6,"title":"Documentation","description":"Complete admission forms if staying"},{"number":7,"title":"Transfer if Needed","description":"Request transfer to specialized hospital if required"}]'::jsonb,
ARRAY['CNIC', 'Sehat Card (if available)', 'Previous medical records (if available)'],
ARRAY['1122', '115', '042-99205282'],
ARRAY['emergency@health.punjab.gov.pk'],
ARRAY['https://health.punjab.gov.pk'],
'Immediate attention for emergencies',
true, 4560, 298, 4.6, '2025-01-14'::date),

-- EDUCATION (20 guides)
('School Admission Process Guide 2025', 'school-admission-process-2025', (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
'Complete guide for admitting your child to government or private schools.',
'[{"number":1,"title":"Research Schools","description":"List schools in your area matching your requirements"},{"number":2,"title":"Check Age Criteria","description":"Verify age requirements for desired class"},{"number":3,"title":"Get Prospectus","description":"Download or collect admission prospectus"},{"number":4,"title":"Prepare Documents","description":"Gather birth certificate, photos, previous records"},{"number":5,"title":"Submit Application","description":"Apply during admission window (usually Dec-March)"},{"number":6,"title":"Entry Test","description":"Child may need to appear for admission test"},{"number":7,"title":"Interview","description":"Parent-child interview at some schools"},{"number":8,"title":"Fee Payment","description":"Pay admission and first term fees"},{"number":9,"title":"Collect Books","description":"Get uniforms and books list"}]'::jsonb,
ARRAY['B-Form/Birth Certificate', 'Passport photos (6)', 'Previous school leaving certificate', 'Parent CNIC copies', 'Immunization record'],
ARRAY['042-99205100', '051-9252051'],
ARRAY['admissions@schools.edu.pk'],
ARRAY['https://schools.punjab.gov.pk'],
'February-April for next session',
true, 5670, 345, 4.5, '2025-01-13'::date),

('Apply for Education Scholarship', 'education-scholarship-2025', (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
'How to apply for government and private education scholarships in Pakistan.',
'[{"number":1,"title":"Research Scholarships","description":"Find scholarships matching your profile on HEC portal"},{"number":2,"title":"Check Eligibility","description":"Review income, merit, and other criteria"},{"number":3,"title":"Prepare Documents","description":"Academic records, income certificates, essays"},{"number":4,"title":"Online Application","description":"Apply through HEC or respective scholarship portal"},{"number":5,"title":"Submit Supporting Docs","description":"Upload or mail required documents"},{"number":6,"title":"Wait for Shortlisting","description":"Shortlisted candidates notified via email/SMS"},{"number":7,"title":"Interview","description":"Appear for interview if called"},{"number":8,"title":"Award Announcement","description":"Selected students receive award letter"}]'::jsonb,
ARRAY['Academic transcripts', 'Income certificate', 'CNIC copy', 'B-Form', 'Recommendation letters', 'Essays/Statement of purpose'],
ARRAY['051-111-119-432', '042-99232260'],
ARRAY['scholarships@hec.gov.pk'],
ARRAY['https://hec.gov.pk/scholarships', 'https://peef.org.pk'],
'Application windows vary by scholarship',
true, 4320, 267, 4.7, '2025-01-11'::date),

('Get School Leaving Certificate', 'school-leaving-certificate', (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
'Process to obtain School Leaving Certificate (SLC) for transfer or records.',
'[{"number":1,"title":"Clear Dues","description":"Ensure all school fees are paid"},{"number":2,"title":"Submit Application","description":"Apply to principal for SLC"},{"number":3,"title":"Return Property","description":"Return library books, ID card, etc."},{"number":4,"title":"Wait Processing","description":"School prepares certificate"},{"number":5,"title":"Verification","description":"Principal verifies and signs"},{"number":6,"title":"Collect Certificate","description":"Get original SLC with school stamp"}]'::jsonb,
ARRAY['Fee clearance receipt', 'Application letter', 'ID card return'],
ARRAY['School specific number'],
ARRAY['admin@school.edu.pk'],
ARRAY['N/A - Visit school directly'],
'3-7 working days',
true, 2890, 156, 4.4, '2025-01-09'::date),

-- SOCIAL CAUSES (25 guides)
('CNIC Application - First Time', 'cnic-first-time-application', (SELECT id FROM categories WHERE slug = 'social-causes' LIMIT 1),
'Complete guide to get your first CNIC from NADRA at age 18.',
'[{"number":1,"title":"Gather Documents","description":"Collect B-Form, parent CNICs, school certificate"},{"number":2,"title":"Visit NADRA Center","description":"Go to nearest NADRA Registration Center"},{"number":3,"title":"Token System","description":"Get token and wait for your turn"},{"number":4,"title":"Fill Application Form","description":"Complete CNIC form with accurate info"},{"number":5,"title":"Biometric Capture","description":"Fingerprints and photo taken digitally"},{"number":6,"title":"Pay Fee","description":"Pay normal (30 days) or urgent (7 days) fee"},{"number":7,"title":"Get Receipt","description":"Keep token receipt for collection"},{"number":8,"title":"Collect CNIC","description":"Return to collect card or opt for delivery"}]'::jsonb,
ARRAY['Original B-Form', 'Parent CNIC copies (both)', '2 passport photos', 'School/College certificate', 'Utility bill for address proof'],
ARRAY['111-786-100', '051-111-786-100'],
ARRAY['helpdesk@nadra.gov.pk'],
ARRAY['https://nadra.gov.pk', 'https://id.nadra.gov.pk'],
'15-30 working days (normal), 7 days (urgent)',
true, 8970, 567, 4.9, '2025-01-15'::date),

('CNIC Modification/Correction', 'cnic-modification-correction', (SELECT id FROM categories WHERE slug = 'social-causes' LIMIT 1),
'How to correct errors or update information on your CNIC.',
'[{"number":1,"title":"Identify Changes","description":"List what needs to be corrected/updated"},{"number":2,"title":"Gather Proof","description":"Get supporting documents for each change"},{"number":3,"title":"Visit NADRA","description":"Go to NADRA center with all documents"},{"number":4,"title":"Fill Modification Form","description":"Complete CNIC modification form"},{"number":5,"title":"Pay Fee","description":"Fee varies based on type of change"},{"number":6,"title":"Biometric Update","description":"Photo retaken if appearance changed"},{"number":7,"title":"Collect New CNIC","description":"New card issued with corrections"}]'::jsonb,
ARRAY['Current CNIC', 'Supporting documents for changes', 'Affidavit (for major changes)', 'Fee challan'],
ARRAY['111-786-100'],
ARRAY['helpdesk@nadra.gov.pk'],
ARRAY['https://nadra.gov.pk'],
'15-30 working days',
true, 4560, 234, 4.6, '2025-01-14'::date),

('Apply for Domicile Certificate', 'domicile-certificate-application', (SELECT id FROM categories WHERE slug = 'social-causes' LIMIT 1),
'Get domicile certificate from District Collector/Commissioner office.',
'[{"number":1,"title":"Determine Eligibility","description":"Must be permanent resident of the district"},{"number":2,"title":"Get Application Form","description":"Download from DC office website or collect physically"},{"number":3,"title":"Prepare Documents","description":"CNIC, education certificates, property proof"},{"number":4,"title":"Get Attestation","description":"Get documents attested by gazetted officer"},{"number":5,"title":"Submit Application","description":"Submit at DC/Commissioner office with fee"},{"number":6,"title":"Verification","description":"Office verifies your residential status"},{"number":7,"title":"Collect Certificate","description":"Receive domicile certificate after verification"}]'::jsonb,
ARRAY['CNIC copy', 'Matric certificate', 'Utility bills (3 months)', '2 passport photos', 'Affidavit of residence', 'Property documents'],
ARRAY['042-99205215', 'DC Office Number'],
ARRAY['dcoffice@punjab.gov.pk'],
ARRAY['https://punjab.gov.pk/domicile'],
'7-15 working days',
true, 5670, 345, 4.5, '2025-01-13'::date),

('BISP/Ehsaas Program Registration', 'bisp-ehsaas-registration-2025', (SELECT id FROM categories WHERE slug = 'social-causes' LIMIT 1),
'Register for Benazir Income Support Program and Ehsaas benefits.',
'[{"number":1,"title":"Check Eligibility","description":"Use NSER survey score or check online"},{"number":2,"title":"Send CNIC SMS","description":"Send CNIC to 8171 to check eligibility status"},{"number":3,"title":"Visit Tehsil Center","description":"If eligible, visit nearest BISP tehsil office"},{"number":4,"title":"Biometric Verification","description":"CNIC and fingerprint verification"},{"number":5,"title":"Registration Complete","description":"Get registered in BISP database"},{"number":6,"title":"Await Payment","description":"Receive SMS when payment is ready"},{"number":7,"title":"Collect Money","description":"Collect from designated payment point with CNIC"}]'::jsonb,
ARRAY['CNIC (mandatory)', 'No other documents required for poor households'],
ARRAY['0800-26477', '8171'],
ARRAY['info@bisp.gov.pk'],
ARRAY['https://bisp.gov.pk', 'https://ehsaas.gov.pk'],
'Registration ongoing, payments quarterly',
true, 7890, 456, 4.7, '2025-01-12'::date),

('Birth Certificate Issuance', 'birth-certificate-issuance', (SELECT id FROM categories WHERE slug = 'social-causes' LIMIT 1),
'Get birth certificate for newborn child from Union Council.',
'[{"number":1,"title":"Hospital Certificate","description":"Get birth certificate from hospital where child was born"},{"number":2,"title":"Visit Union Council","description":"Go to your local Union Council office"},{"number":3,"title":"Fill Form","description":"Complete birth registration form"},{"number":4,"title":"Provide Documents","description":"Parent CNICs, hospital certificate, nikah nama"},{"number":5,"title":"Pay Fee","description":"Pay nominal registration fee"},{"number":6,"title":"Get Certificate","description":"Receive birth certificate/B-Form"}]'::jsonb,
ARRAY['Hospital birth certificate', 'Parent CNIC copies', 'Nikah Nama copy', 'Vaccination card'],
ARRAY['Union Council Number'],
ARRAY['nadra@nadra.gov.pk'],
ARRAY['N/A - Visit Union Council'],
'Same day to 3 working days',
true, 4320, 267, 4.8, '2025-01-10'::date),

('Death Certificate Registration', 'death-certificate-registration', (SELECT id FROM categories WHERE slug = 'social-causes' LIMIT 1),
'Register death and obtain death certificate from Union Council.',
'[{"number":1,"title":"Hospital Certificate","description":"Get death certificate from hospital/doctor"},{"number":2,"title":"Report to Police","description":"In case of unnatural death, file FIR"},{"number":3,"title":"Visit Union Council","description":"Go to Union Council with documents"},{"number":4,"title":"Fill Death Form","description":"Complete death registration form"},{"number":5,"title":"Provide Documents","description":"Submit death certificate, deceased CNIC, informant CNIC"},{"number":6,"title":"Get Registration","description":"Receive death certificate"}]'::jsonb,
ARRAY['Hospital death certificate', 'Deceased CNIC', 'Informant CNIC', 'FIR (if applicable)'],
ARRAY['Union Council Number'],
ARRAY['nadra@nadra.gov.pk'],
ARRAY['N/A - Visit Union Council'],
'Same day to 3 working days',
true, 2340, 123, 4.5, '2025-01-08'::date),

('Passport Application Online', 'passport-application-online-2025', (SELECT id FROM categories WHERE slug = 'social-causes' LIMIT 1),
'Complete guide to apply for Pakistani passport through online portal.',
'[{"number":1,"title":"Create Account","description":"Register on passport.gov.pk portal"},{"number":2,"title":"Fill Application","description":"Complete online application form carefully"},{"number":3,"title":"Upload Photo","description":"Upload passport-size photo as per specs"},{"number":4,"title":"Pay Fee Online","description":"Pay fee via bank or JazzCash/EasyPaisa"},{"number":5,"title":"Book Appointment","description":"Select date and passport office location"},{"number":6,"title":"Visit Office","description":"Go on appointment date with original documents"},{"number":7,"title":"Biometric Capture","description":"Photo and fingerprints taken"},{"number":8,"title":"Collect Passport","description":"Receive in 15-21 days or opt for urgent"}]'::jsonb,
ARRAY['CNIC original', 'Old passport (if renewal)', 'NICOP (for overseas)', 'Matric certificate', 'Documents for government employees'],
ARRAY['051-111-243-243', '042-111-243-243'],
ARRAY['info@dgip.gov.pk'],
ARRAY['https://passport.gov.pk', 'https://onlinevisa.dgip.gov.pk'],
'15-21 working days (normal), 3-5 days (urgent)',
true, 6780, 412, 4.7, '2025-01-07'::date),

-- LEGAL & RIGHTS (20 guides)
('How to File FIR at Police Station', 'how-to-file-fir', (SELECT id FROM categories WHERE slug = 'legal-rights' LIMIT 1),
'Complete guide to registering First Information Report for crimes.',
'[{"number":1,"title":"Go to Police Station","description":"Visit police station in jurisdiction where crime occurred"},{"number":2,"title":"Meet SHO/Duty Officer","description":"Request to file FIR with officer on duty"},{"number":3,"title":"Narrate Incident","description":"Give complete details of what happened"},{"number":4,"title":"Provide Evidence","description":"Submit any evidence, photos, witnesses"},{"number":5,"title":"Get FIR Registered","description":"Officer writes FIR and reads it back"},{"number":6,"title":"Sign FIR","description":"Sign after verifying all details are correct"},{"number":7,"title":"Get Copy","description":"Get copy of FIR (your legal right)"},{"number":8,"title":"Follow Up","description":"Note investigating officer name and contact"}]'::jsonb,
ARRAY['CNIC copy', 'Written complaint (optional)', 'Evidence documents/photos', 'Witness details'],
ARRAY['15', '8787', '042-99205256'],
ARRAY['complaints@punjabpolice.gov.pk'],
ARRAY['https://punjabpolice.gov.pk', 'https://citizenportal.gov.pk'],
'Must be registered immediately by law',
true, 5670, 389, 4.6, '2025-01-14'::date),

('Consumer Court Complaint Filing', 'consumer-court-complaint', (SELECT id FROM categories WHERE slug = 'legal-rights' LIMIT 1),
'How to file complaint in Consumer Court for fraud, defective products, or bad services.',
'[{"number":1,"title":"Gather Evidence","description":"Collect receipts, warranties, photos of defective item"},{"number":2,"title":"Send Legal Notice","description":"Send notice to seller/company asking for remedy"},{"number":3,"title":"Wait 15 Days","description":"Give them time to respond"},{"number":4,"title":"File Complaint","description":"If not resolved, file complaint in Consumer Court"},{"number":5,"title":"Pay Court Fee","description":"Pay nominal filing fee (1% of claim, max Rs 25,000)"},{"number":6,"title":"Attach Documents","description":"Submit all evidence with complaint"},{"number":7,"title":"Attend Hearings","description":"Appear on hearing dates"},{"number":8,"title":"Get Order","description":"Court issues order if complaint is valid"}]'::jsonb,
ARRAY['Purchase receipt/invoice', 'Product photos', 'Warranty card', 'Written communication with seller', 'Legal notice copy'],
ARRAY['042-99232025', '051-9211425'],
ARRAY['consumercourt@punjab.gov.pk'],
ARRAY['https://pca.punjab.gov.pk'],
'3-6 months typically',
true, 3450, 198, 4.4, '2025-01-12'::date),

('Cyber Crime Reporting to FIA', 'cyber-crime-reporting-fia', (SELECT id FROM categories WHERE slug = 'legal-rights' LIMIT 1),
'Report online fraud, harassment, hacking, or cyber crime to FIA.',
'[{"number":1,"title":"Document Everything","description":"Screenshot messages, emails, social media posts"},{"number":2,"title":"Online Complaint","description":"File on FIA Cyber Crime portal fia.gov.pk"},{"number":3,"title":"Provide Details","description":"Give complete information about incident"},{"number":4,"title":"Attach Evidence","description":"Upload screenshots, links, account details"},{"number":5,"title":"Get Reference Number","description":"Save complaint reference number"},{"number":6,"title":"Physical Visit","description":"May need to visit FIA Cyber Crime Circle"},{"number":7,"title":"Investigation","description":"FIA investigates and takes action"},{"number":8,"title":"Follow Up","description":"Check status using reference number"}]'::jsonb,
ARRAY['Screenshots of harassment/fraud', 'URL links', 'Account details of accused', 'Your CNIC copy', 'Phone records if applicable'],
ARRAY['9911', '051-9261686'],
ARRAY['complaint@fia.gov.pk', 'cybercrime@fia.gov.pk'],
ARRAY['https://complaint.fia.gov.pk'],
'1-3 months for investigation',
true, 4120, 267, 4.5, '2025-01-10'::date),

-- PROPERTY & LAND (15 guides)
('Property Sale Deed Registration', 'property-sale-deed-registration', (SELECT id FROM categories WHERE slug = 'property-land' LIMIT 1),
'Complete process for registering property sale at Registrar office.',
'[{"number":1,"title":"Verify Ownership","description":"Check property records at Patwari/DHA office"},{"number":2,"title":"Draft Sale Deed","description":"Get sale deed drafted by lawyer"},{"number":3,"title":"Calculate Duty","description":"Calculate stamp duty and capital gains tax"},{"number":4,"title":"Pay Taxes","description":"Pay CVT, stamp duty, and CGT at bank"},{"number":5,"title":"Book Appointment","description":"Schedule appointment at Sub-Registrar office"},{"number":6,"title":"Both Parties Appear","description":"Buyer, seller, witnesses must be present"},{"number":7,"title":"Biometric Verification","description":"NADRA verification of all parties"},{"number":8,"title":"Sign Documents","description":"Sign deed in presence of Registrar"},{"number":9,"title":"Get Registered Deed","description":"Collect registered sale deed"}]'::jsonb,
ARRAY['Original property documents', 'Both parties CNIC', 'Tax paid challans', 'Two witnesses with CNIC', 'NOC from society (if applicable)', 'Passport photos'],
ARRAY['042-99205378', 'Revenue department number'],
ARRAY['registrar@punjab.gov.pk'],
ARRAY['https://punjab.gov.pk/revenue', 'https://e-stamping.punjab.gov.pk'],
'Same day if documents complete',
true, 4560, 289, 4.5, '2025-01-13'::date),

('Mutation/Intaqal of Property', 'property-mutation-intaqal', (SELECT id FROM categories WHERE slug = 'property-land' LIMIT 1),
'Transfer property ownership in land records after purchase or inheritance.',
'[{"number":1,"title":"Get Registered Deed","description":"Have sale deed registered at Registrar office"},{"number":2,"title":"Apply for Mutation","description":"Submit application to Patwari Halqa"},{"number":3,"title":"Pay Fee","description":"Pay mutation fee"},{"number":4,"title":"Patwari Verification","description":"Patwari verifies documents and prepares report"},{"number":5,"title":"Tehsildar Approval","description":"Case goes to Tehsildar for approval"},{"number":6,"title":"Public Notice","description":"Notice published for objections"},{"number":7,"title":"Hearing","description":"If no objection, mutation sanctioned"},{"number":8,"title":"Entry in Record","description":"New owner name entered in Fard"}]'::jsonb,
ARRAY['Registered sale deed', 'Seller Fard', 'CNIC copies', 'Previous Fard of land', 'Death certificate (if inheritance)'],
ARRAY['Revenue office number', '042-99205378'],
ARRAY['revenue@punjab.gov.pk'],
ARRAY['https://lrs.punjab.gov.pk'],
'15-30 days if no objection',
true, 3890, 234, 4.4, '2025-01-11'::date),

('Online Fard (Land Record) Request', 'online-fard-land-record', (SELECT id FROM categories WHERE slug = 'property-land' LIMIT 1),
'Get computerized copy of land record (Fard) from Punjab Land Record Authority.',
'[{"number":1,"title":"Visit PLRA Website","description":"Go to lrs.punjab.gov.pk or PLRA center"},{"number":2,"title":"Enter Land Details","description":"Provide district, tehsil, mouza, and khewat number"},{"number":3,"title":"Pay Fee","description":"Pay nominal fee online or at center"},{"number":4,"title":"Biometric Verification","description":"Verify identity via CNIC biometric"},{"number":5,"title":"Get Fard","description":"Receive computerized Fard instantly"},{"number":6,"title":"Verify Fard","description":"Cross-check details before leaving"}]'::jsonb,
ARRAY['CNIC', 'Land details (khewat/khasra number)', 'Fee payment'],
ARRAY['042-111-577-277', 'PLRA Center number'],
ARRAY['info@plra.punjab.gov.pk'],
ARRAY['https://lrs.punjab.gov.pk'],
'Instant at centers',
true, 5670, 378, 4.8, '2025-01-09'::date)

ON CONFLICT (slug) DO UPDATE SET 
  views_count = EXCLUDED.views_count,
  upvotes_count = EXCLUDED.upvotes_count,
  updated_at = now();

-- Note: This file contains 35 core guides. 
-- Continue adding more guides in seed_guides_part2.sql to reach 150 total.
