-- Issue Guides Seed Data Part 2 - CitizenConnect
-- Additional guides to complete 150 total
-- Run this after seed_guides.sql

INSERT INTO public.guides (title, slug, category_id, problem_explanation, steps, required_documents, contact_phones, contact_emails, online_portals, timeline_expectation, is_published, views_count, upvotes_count, average_rating, created_at) VALUES

-- MORE ROADS & TRANSPORT
('Motorcycle Registration Process', 'motorcycle-registration-2025', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'How to register a new motorcycle with Excise Department.',
'[{"number":1,"title":"Get Invoice","description":"Original invoice from authorized dealer"},{"number":2,"title":"Apply at Excise","description":"Submit application at Motor Registration Authority"},{"number":3,"title":"Pay Registration","description":"Pay registration and token tax"},{"number":4,"title":"Get Number Plates","description":"Collect registration book and number plates"}]'::jsonb,
ARRAY['Purchase invoice', 'CNIC copy', 'Dealer letter'],
ARRAY['042-99203259'],
ARRAY['info@excise.punjab.gov.pk'],
ARRAY['https://excise.punjab.gov.pk'],
'3-5 working days', true, 3200, 189, 4.5, '2025-01-12'::date),

('Uber/Careem Driver Registration', 'uber-careem-driver-registration', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'Complete guide to become a ride-hailing driver in Pakistan.',
'[{"number":1,"title":"Check Requirements","description":"Valid license, own vehicle, smartphone"},{"number":2,"title":"Apply Online","description":"Register on Uber/Careem driver app"},{"number":3,"title":"Submit Documents","description":"Upload license, CNIC, vehicle papers"},{"number":4,"title":"Background Check","description":"Company verifies your background"},{"number":5,"title":"Training Session","description":"Attend mandatory training"},{"number":6,"title":"Account Activation","description":"Start accepting rides"}]'::jsonb,
ARRAY['Driving license', 'Vehicle registration', 'CNIC', 'Police verification'],
ARRAY['042-111-227336'],
ARRAY['support@careem.com'],
ARRAY['https://drive.uber.com', 'https://careem.com/captain'],
'7-14 days for approval', true, 2890, 167, 4.4, '2025-01-10'::date),

('Vehicle Fitness Test Guide', 'vehicle-fitness-test', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'Annual fitness test requirements for vehicles over 10 years old.',
'[{"number":1,"title":"Check Eligibility","description":"Vehicles over 10 years require annual fitness"},{"number":2,"title":"Book Inspection","description":"Schedule at authorized inspection station"},{"number":3,"title":"Prepare Vehicle","description":"Ensure brakes, lights, emissions are good"},{"number":4,"title":"Pay Fee","description":"Pay inspection fee"},{"number":5,"title":"Pass Inspection","description":"Get fitness certificate if passed"}]'::jsonb,
ARRAY['Registration book', 'Insurance', 'Token tax receipt'],
ARRAY['042-99203259'],
ARRAY['motorvehicle@excise.punjab.gov.pk'],
ARRAY['https://excise.punjab.gov.pk'],
'Same day', true, 1560, 89, 4.3, '2025-01-08'::date),

('Apply for Route Permit Public Transport', 'route-permit-public-transport', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'Get route permit for operating bus, van, or wagon on specific route.',
'[{"number":1,"title":"Check Route Availability","description":"Verify if permits available for desired route"},{"number":2,"title":"Apply to RTA","description":"Submit application to Regional Transport Authority"},{"number":3,"title":"Vehicle Inspection","description":"Vehicle inspected for roadworthiness"},{"number":4,"title":"Pay Permit Fee","description":"Pay annual permit charges"},{"number":5,"title":"Get Permit","description":"Receive route permit valid for 1 year"}]'::jsonb,
ARRAY['Vehicle registration', 'Fitness certificate', 'CNIC', 'Route details'],
ARRAY['042-99205100'],
ARRAY['rta@transport.punjab.gov.pk'],
ARRAY['https://transport.punjab.gov.pk'],
'7-15 working days', true, 980, 56, 4.1, '2025-01-06'::date),

('Report Traffic Challan Dispute', 'traffic-challan-dispute', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'How to dispute wrongly issued traffic challan or e-challan.',
'[{"number":1,"title":"Note Challan Details","description":"Get challan number, date, violation type"},{"number":2,"title":"Gather Evidence","description":"Photos/video proving innocence"},{"number":3,"title":"File Written Objection","description":"Submit to SSP Traffic within 30 days"},{"number":4,"title":"Hearing Scheduled","description":"Appear before Traffic Magistrate"},{"number":5,"title":"Present Case","description":"Show evidence at hearing"},{"number":6,"title":"Decision","description":"Challan waived or confirmed"}]'::jsonb,
ARRAY['Original challan', 'Evidence photos/video', 'CNIC', 'Objection letter'],
ARRAY['1737', '042-99213144'],
ARRAY['complaints@trafficpolice.punjab.gov.pk'],
ARRAY['https://punjabtrafficpolice.gov.pk'],
'15-30 days for hearing', true, 2340, 145, 4.2, '2025-01-05'::date),

-- MORE SEWERAGE & WATER
('Water Meter Reading Complaint', 'water-meter-reading-complaint', (SELECT id FROM categories WHERE slug = 'sewerage-water' LIMIT 1),
'Report incorrect water meter reading or faulty meter.',
'[{"number":1,"title":"Read Your Meter","description":"Note current reading on meter"},{"number":2,"title":"Compare with Bill","description":"Check if bill matches actual reading"},{"number":3,"title":"File Complaint","description":"Report to WASA billing section"},{"number":4,"title":"Meter Testing","description":"Request meter accuracy test"},{"number":5,"title":"Get Adjustment","description":"Bill adjusted based on correct reading"}]'::jsonb,
ARRAY['Recent water bills', 'Photo of meter reading', 'Consumer number'],
ARRAY['1334', '042-99210243'],
ARRAY['billing@wasa.punjab.gov.pk'],
ARRAY['https://wasa.punjab.gov.pk'],
'7-10 working days', true, 1890, 112, 4.3, '2025-01-11'::date),

('Tanker Water Supply Request', 'tanker-water-supply-request', (SELECT id FROM categories WHERE slug = 'sewerage-water' LIMIT 1),
'Request WASA water tanker for emergency water supply.',
'[{"number":1,"title":"Call WASA Helpline","description":"Contact emergency water supply number"},{"number":2,"title":"Provide Details","description":"Give address and reason for request"},{"number":3,"title":"Confirm Availability","description":"Check tanker availability"},{"number":4,"title":"Wait for Delivery","description":"Tanker dispatched within hours"}]'::jsonb,
ARRAY['Consumer ID (if applicable)', 'Address details'],
ARRAY['1334', '042-99210250'],
ARRAY['tanker@wasa.punjab.gov.pk'],
ARRAY['https://wasa.punjab.gov.pk'],
'Same day in most areas', true, 1230, 78, 4.0, '2025-01-09'::date),

('Illegal Sewerage Connection Report', 'illegal-sewerage-connection-report', (SELECT id FROM categories WHERE slug = 'sewerage-water' LIMIT 1),
'Report unauthorized sewerage connections or line tapping.',
'[{"number":1,"title":"Document Issue","description":"Take photos if safe to do so"},{"number":2,"title":"Note Location","description":"Exact address of illegal connection"},{"number":3,"title":"Report to WASA","description":"File complaint via phone or online"},{"number":4,"title":"Inspection Team","description":"WASA team investigates"},{"number":5,"title":"Action Taken","description":"Illegal connection removed, fine imposed"}]'::jsonb,
ARRAY['Photos (optional)', 'Location details'],
ARRAY['1334', '042-99210243'],
ARRAY['complaints@wasa.punjab.gov.pk'],
ARRAY['https://wasa.punjab.gov.pk'],
'3-7 working days', true, 670, 34, 4.1, '2025-01-07'::date),

-- MORE ELECTRICITY & GAS
('Report Power Outage/Load Shedding', 'report-power-outage', (SELECT id FROM categories WHERE slug = 'electricity-gas' LIMIT 1),
'Complain about unscheduled power outages or excessive load shedding.',
'[{"number":1,"title":"Check Schedule","description":"Verify if scheduled load shedding or fault"},{"number":2,"title":"Call Helpline","description":"Report to DISCO customer care"},{"number":3,"title":"Note Complaint","description":"Get complaint number"},{"number":4,"title":"Track Status","description":"Follow up if not restored in time"}]'::jsonb,
ARRAY['Consumer number', 'Feeder/area information'],
ARRAY['118', '042-99205243'],
ARRAY['complaints@lesco.gov.pk'],
ARRAY['https://lesco.gov.pk'],
'1-4 hours for faults', true, 5670, 345, 4.5, '2025-01-13'::date),

('Apply for Net Metering Solar', 'net-metering-solar-application', (SELECT id FROM categories WHERE slug = 'electricity-gas' LIMIT 1),
'Install solar panels and sell excess electricity to grid.',
'[{"number":1,"title":"Get Solar Assessment","description":"Calculate your solar potential"},{"number":2,"title":"Choose Installer","description":"Select AEDB certified solar company"},{"number":3,"title":"Apply to DISCO","description":"Submit net metering application"},{"number":4,"title":"Pay Fees","description":"Pay generation license fee"},{"number":5,"title":"Install System","description":"Solar company installs panels"},{"number":6,"title":"Inspection","description":"DISCO inspects installation"},{"number":7,"title":"Get Bidirectional Meter","description":"DISCO installs net meter"},{"number":8,"title":"Start Exporting","description":"Begin selling excess power"}]'::jsonb,
ARRAY['Property ownership proof', 'CNIC', 'Electricity bill', 'Solar quotation', 'Building plan'],
ARRAY['051-9206600', '042-99205243'],
ARRAY['netmetering@aedb.org'],
ARRAY['https://aedb.org', 'https://lesco.gov.pk/netmetering'],
'45-60 days total process', true, 2340, 156, 4.6, '2025-01-12'::date),

('Transfer Electricity Connection', 'transfer-electricity-connection', (SELECT id FROM categories WHERE slug = 'electricity-gas' LIMIT 1),
'Change electricity connection name after property purchase.',
'[{"number":1,"title":"Get Clear Bill","description":"Clear all pending bills first"},{"number":2,"title":"Prepare Documents","description":"Sale deed, both parties CNIC"},{"number":3,"title":"Apply for Transfer","description":"Submit application at SDO office"},{"number":4,"title":"Pay Transfer Fee","description":"Pay nominal transfer charges"},{"number":5,"title":"Verification","description":"Previous owner consent verified"},{"number":6,"title":"Name Changed","description":"Connection transferred to new owner"}]'::jsonb,
ARRAY['Registered sale deed', 'Both parties CNIC', 'Clear bill receipt', 'NOC from seller'],
ARRAY['118', '042-99205243'],
ARRAY['transfer@lesco.gov.pk'],
ARRAY['https://lesco.gov.pk'],
'7-10 working days', true, 1890, 112, 4.4, '2025-01-10'::date),

('Gas Meter Slow Reading Complaint', 'gas-meter-slow-reading', (SELECT id FROM categories WHERE slug = 'electricity-gas' LIMIT 1),
'Report gas meter tampering or slow reading suspicion.',
'[{"number":1,"title":"Monitor Usage","description":"Compare gas usage with neighbors"},{"number":2,"title":"Check Meter","description":"See if meter moves normally"},{"number":3,"title":"File Complaint","description":"Report to SNGPL/SSGC"},{"number":4,"title":"Meter Testing","description":"Company tests meter accuracy"},{"number":5,"title":"Bill Adjustment","description":"Back-billing if tampering found"}]'::jsonb,
ARRAY['Gas bills (6 months)', 'Photo of meter'],
ARRAY['1199', '042-99260101'],
ARRAY['complaints@sngpl.com.pk'],
ARRAY['https://sngpl.com.pk'],
'7-14 days for testing', true, 890, 56, 4.2, '2025-01-08'::date),

-- MORE HEALTHCARE
('Public Hospital OPD Registration', 'hospital-opd-registration', (SELECT id FROM categories WHERE slug = 'healthcare' LIMIT 1),
'How to register for outpatient treatment at government hospital.',
'[{"number":1,"title":"Visit Early","description":"Reach hospital early morning for token"},{"number":2,"title":"Get Registration","description":"Register at OPD counter with CNIC"},{"number":3,"title":"Pay Token Fee","description":"Pay nominal OPD fee (usually Rs 10-20)"},{"number":4,"title":"Wait for Turn","description":"Sit in waiting area"},{"number":5,"title":"See Doctor","description":"Consult doctor when called"},{"number":6,"title":"Get Prescription","description":"Collect prescription and tests"}]'::jsonb,
ARRAY['CNIC', 'Previous medical records (if any)'],
ARRAY['Hospital number', '042-99205282'],
ARRAY['info@health.punjab.gov.pk'],
ARRAY['https://health.punjab.gov.pk'],
'Same day treatment', true, 4560, 278, 4.5, '2025-01-11'::date),

('Free Medicine from Government Hospital', 'free-medicine-government-hospital', (SELECT id FROM categories WHERE slug = 'healthcare' LIMIT 1),
'Get free or subsidized medicines from government hospital pharmacy.',
'[{"number":1,"title":"Get Prescription","description":"Doctor prescription from OPD/emergency"},{"number":2,"title":"Go to Pharmacy","description":"Visit hospital pharmacy window"},{"number":3,"title":"Submit Prescription","description":"Give prescription to pharmacist"},{"number":4,"title":"Check Availability","description":"Pharmacist checks medicine stock"},{"number":5,"title":"Collect Medicine","description":"Receive free/subsidized medicines"}]'::jsonb,
ARRAY['Doctor prescription', 'OPD slip', 'CNIC (sometimes)'],
ARRAY['Hospital pharmacy number'],
ARRAY['pharmacy@health.punjab.gov.pk'],
ARRAY['https://health.punjab.gov.pk'],
'Same day', true, 3450, 212, 4.3, '2025-01-09'::date),

('Complaint Against Hospital/Doctor', 'complaint-against-hospital-doctor', (SELECT id FROM categories WHERE slug = 'healthcare' LIMIT 1),
'File complaint for medical negligence or poor treatment.',
'[{"number":1,"title":"Document Issue","description":"Collect medical records, prescriptions"},{"number":2,"title":"Write Complaint","description":"Draft detailed written complaint"},{"number":3,"title":"File with DG Health","description":"Submit to Director General Health office"},{"number":4,"title":"PMDC Complaint","description":"For doctor misconduct, file with PMDC"},{"number":5,"title":"Legal Action","description":"Consult lawyer for civil/criminal action"}]'::jsonb,
ARRAY['Medical records', 'Bills/receipts', 'Witness statements', 'Photos if relevant'],
ARRAY['051-9216654', '042-99205282'],
ARRAY['complaints@pmdc.org.pk'],
ARRAY['https://pmdc.org.pk', 'https://health.punjab.gov.pk'],
'30-90 days for investigation', true, 1780, 98, 4.2, '2025-01-07'::date),

-- MORE EDUCATION
('Apply for Merit Scholarship HEC', 'merit-scholarship-hec', (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
'Apply for Higher Education Commission merit-based scholarships.',
'[{"number":1,"title":"Check Eligibility","description":"Review HEC scholarship criteria"},{"number":2,"title":"Prepare Documents","description":"Transcripts, income proof, essays"},{"number":3,"title":"Apply Online","description":"Submit on HEC scholarship portal"},{"number":4,"title":"Upload Documents","description":"Attach all required documents"},{"number":5,"title":"Wait for Results","description":"Merit list announced on website"}]'::jsonb,
ARRAY['Academic transcripts', 'Income certificate', 'CNIC', 'Domicile'],
ARRAY['051-111-119-432'],
ARRAY['scholarships@hec.gov.pk'],
ARRAY['https://hec.gov.pk/scholarships'],
'Varies by scholarship cycle', true, 3890, 234, 4.6, '2025-01-10'::date),

('Duplicate Degree Certificate Request', 'duplicate-degree-certificate', (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
'Get duplicate degree if original is lost or damaged.',
'[{"number":1,"title":"File FIR","description":"Report loss at police station"},{"number":2,"title":"Apply to University","description":"Submit duplicate degree application"},{"number":3,"title":"Pay Fee","description":"Pay duplicate degree fee"},{"number":4,"title":"Verification","description":"University verifies records"},{"number":5,"title":"Get Duplicate","description":"Collect duplicate degree"}]'::jsonb,
ARRAY['FIR copy', 'Original marksheet copies', 'CNIC', 'Application form'],
ARRAY['University helpline'],
ARRAY['registrar@university.edu.pk'],
ARRAY['University website'],
'15-30 working days', true, 2560, 156, 4.4, '2025-01-08'::date),

('HEC Degree Attestation Process', 'hec-degree-attestation', (SELECT id FROM categories WHERE slug = 'education' LIMIT 1),
'Get your degree attested from Higher Education Commission.',
'[{"number":1,"title":"Online Application","description":"Apply on HEC verification portal"},{"number":2,"title":"Pay Fee Online","description":"Pay attestation fee via bank"},{"number":3,"title":"Submit Documents","description":"Upload degree, transcript, CNIC"},{"number":4,"title":"Courier Originals","description":"Send original documents via registered post"},{"number":5,"title":"Processing","description":"HEC verifies documents"},{"number":6,"title":"Collect Attested Degree","description":"Receive via courier or collect"}]'::jsonb,
ARRAY['Original degree', 'Transcript', 'CNIC copy', 'Photo'],
ARRAY['051-111-119-432'],
ARRAY['attestation@hec.gov.pk'],
ARRAY['https://attestation.hec.gov.pk'],
'7-15 working days', true, 4120, 267, 4.7, '2025-01-06'::date),

-- MORE SOCIAL CAUSES
('CNIC for Overseas Pakistanis (NICOP)', 'nicop-overseas-pakistanis', (SELECT id FROM categories WHERE slug = 'social-causes' LIMIT 1),
'Apply for NICOP while living abroad.',
'[{"number":1,"title":"Apply Online","description":"Visit id.nadra.gov.pk for online application"},{"number":2,"title":"Fill Form","description":"Complete NICOP application form"},{"number":3,"title":"Upload Documents","description":"Scan and upload required documents"},{"number":4,"title":"Pay Fee","description":"Pay via international card"},{"number":5,"title":"Visit POC","description":"Go to Pakistan Embassy/Consulate"},{"number":6,"title":"Biometric Capture","description":"Photo and fingerprints taken"},{"number":7,"title":"Delivery","description":"NICOP delivered to your address"}]'::jsonb,
ARRAY['Old CNIC/NICOP', 'Passport copy', 'Photos', 'Visa/work permit copy'],
ARRAY['111-786-100', 'Embassy number'],
ARRAY['nicop@nadra.gov.pk'],
ARRAY['https://id.nadra.gov.pk'],
'21-30 days delivery abroad', true, 3670, 223, 4.6, '2025-01-11'::date),

('Pakistan Origin Card (POC) Application', 'pakistan-origin-card-poc', (SELECT id FROM categories WHERE slug = 'social-causes' LIMIT 1),
'Apply for POC as foreign national of Pakistani origin.',
'[{"number":1,"title":"Check Eligibility","description":"Must be former Pakistani or spouse/child"},{"number":2,"title":"Apply Online","description":"Submit on NADRA POC portal"},{"number":3,"title":"Documents Upload","description":"Proof of Pakistani origin required"},{"number":4,"title":"Pay Fee","description":"Pay POC fee online"},{"number":5,"title":"Biometric at Embassy","description":"Visit nearest Pakistan mission"},{"number":6,"title":"Get POC","description":"Receive POC card via delivery"}]'::jsonb,
ARRAY['Foreign passport', 'Proof of Pakistani origin', 'Photos', 'Parent/spouse documents'],
ARRAY['111-786-100'],
ARRAY['poc@nadra.gov.pk'],
ARRAY['https://id.nadra.gov.pk/poc'],
'30-45 days', true, 1890, 112, 4.5, '2025-01-09'::date),

('Senior Citizen Card Application', 'senior-citizen-card', (SELECT id FROM categories WHERE slug = 'social-causes' LIMIT 1),
'Apply for CNIC with Senior Citizen status for 60+ citizens.',
'[{"number":1,"title":"Eligibility","description":"Age 60 years or above"},{"number":2,"title":"Visit NADRA","description":"Go to NADRA center with CNIC"},{"number":3,"title":"Apply for Renewal","description":"Request Senior Citizen card"},{"number":4,"title":"Pay Fee","description":"Reduced fee for senior citizens"},{"number":5,"title":"Get New Card","description":"Card with special status issued"}]'::jsonb,
ARRAY['Current CNIC', 'Age proof (if needed)'],
ARRAY['111-786-100'],
ARRAY['helpdesk@nadra.gov.pk'],
ARRAY['https://nadra.gov.pk'],
'15-20 working days', true, 1230, 78, 4.4, '2025-01-07'::date),

('Marriage Registration (Nikah Nama)', 'marriage-registration-nikah-nama', (SELECT id FROM categories WHERE slug = 'social-causes' LIMIT 1),
'Register marriage and get official Nikah Nama.',
'[{"number":1,"title":"Hire Nikah Registrar","description":"Contact licensed Nikah Khawan"},{"number":2,"title":"Prepare Documents","description":"Both parties CNIC, witnesses"},{"number":3,"title":"Nikah Ceremony","description":"Perform nikah with registrar"},{"number":4,"title":"Sign Nikah Nama","description":"All parties sign the document"},{"number":5,"title":"Register at UC","description":"Registrar submits to Union Council"},{"number":6,"title":"Get Certificate","description":"Collect registered Nikah Nama"}]'::jsonb,
ARRAY['Both parties CNIC', 'Witnesses CNIC (2 each)', 'Photos', 'Divorce certificate (if applicable)'],
ARRAY['Union Council number'],
ARRAY['N/A'],
ARRAY['N/A'],
'7 days for registration', true, 2780, 167, 4.6, '2025-01-05'::date),

('Divorce Certificate Issuance', 'divorce-certificate-issuance', (SELECT id FROM categories WHERE slug = 'social-causes' LIMIT 1),
'Get official divorce certificate from Union Council.',
'[{"number":1,"title":"Notice Period","description":"90 days notice required by law"},{"number":2,"title":"Submit at UC","description":"Husband sends notice to UC"},{"number":3,"title":"UC Informs Wife","description":"Union Council notifies wife"},{"number":4,"title":"Reconciliation Attempt","description":"UC may arrange arbitration"},{"number":5,"title":"After 90 Days","description":"Divorce becomes effective"},{"number":6,"title":"Get Certificate","description":"Divorce certificate issued"}]'::jsonb,
ARRAY['Nikah Nama copy', 'Both parties CNIC', 'Written notice'],
ARRAY['Union Council number'],
ARRAY['N/A'],
ARRAY['N/A'],
'90 days minimum by law', true, 1560, 89, 4.2, '2025-01-03'::date),

-- MORE LEGAL & RIGHTS
('Apply for Free Legal Aid', 'apply-free-legal-aid', (SELECT id FROM categories WHERE slug = 'legal-rights' LIMIT 1),
'Get free lawyer for civil or criminal case from Legal Aid Office.',
'[{"number":1,"title":"Check Eligibility","description":"Income below certain threshold"},{"number":2,"title":"Visit Legal Aid Office","description":"Go to District Legal Aid Office"},{"number":3,"title":"Submit Application","description":"Apply for free legal representation"},{"number":4,"title":"Income Verification","description":"Submit income proof"},{"number":5,"title":"Lawyer Assigned","description":"Free lawyer appointed for your case"}]'::jsonb,
ARRAY['CNIC', 'Income certificate', 'Case details', 'Poverty certificate'],
ARRAY['042-99205256'],
ARRAY['legalaid@pjb.gov.pk'],
ARRAY['https://pjb.gov.pk/legalaid'],
'7-14 days for lawyer assignment', true, 1230, 78, 4.3, '2025-01-10'::date),

('Bail Application Process', 'bail-application-process', (SELECT id FROM categories WHERE slug = 'legal-rights' LIMIT 1),
'Understanding bail types and application process in Pakistan.',
'[{"number":1,"title":"Arrest Stage","description":"Police can grant station bail for minor offenses"},{"number":2,"title":"Remand Stage","description":"Apply to Magistrate for pre-arrest bail"},{"number":3,"title":"Hire Lawyer","description":"Get lawyer to file bail application"},{"number":4,"title":"Submit Application","description":"File in relevant court"},{"number":5,"title":"Surety Bonds","description":"Arrange surety bonds as required"},{"number":6,"title":"Court Hearing","description":"Appear when bail heard"},{"number":7,"title":"Bail Granted","description":"Released on bail if approved"}]'::jsonb,
ARRAY['FIR copy', 'Lawyer authority letter', 'Surety documents', 'CNIC'],
ARRAY['District courts number'],
ARRAY['N/A'],
ARRAY['N/A'],
'1-7 days for bail hearing', true, 2340, 145, 4.4, '2025-01-08'::date),

('Landlord-Tenant Dispute Resolution', 'landlord-tenant-dispute', (SELECT id FROM categories WHERE slug = 'legal-rights' LIMIT 1),
'Resolve rent disputes through Rent Controller court.',
'[{"number":1,"title":"Try Negotiation","description":"Attempt to settle matter directly first"},{"number":2,"title":"Legal Notice","description":"Send legal notice to other party"},{"number":3,"title":"File Case","description":"Approach Rent Controller if notice fails"},{"number":4,"title":"Submit Documents","description":"Rent agreement, payment receipts"},{"number":5,"title":"Hearing Process","description":"Both parties present case"},{"number":6,"title":"Court Order","description":"Rent Controller gives binding decision"}]'::jsonb,
ARRAY['Rent agreement', 'Payment receipts', 'Utility bills', 'CNIC', 'Legal notice copy'],
ARRAY['Rent Controller office number'],
ARRAY['N/A'],
ARRAY['N/A'],
'30-90 days for decision', true, 1890, 112, 4.3, '2025-01-06'::date),

('Writ Petition in High Court', 'writ-petition-high-court', (SELECT id FROM categories WHERE slug = 'legal-rights' LIMIT 1),
'File writ petition against government actions in High Court.',
'[{"number":1,"title":"Grounds Assessment","description":"Determine if case qualifies for writ"},{"number":2,"title":"Hire Lawyer","description":"Engage advocate with High Court license"},{"number":3,"title":"Draft Petition","description":"Lawyer prepares writ petition"},{"number":4,"title":"Pay Court Fee","description":"Pay required court fees"},{"number":5,"title":"Filing","description":"Petition filed in High Court registry"},{"number":6,"title":"Hearing","description":"Case heard by High Court bench"},{"number":7,"title":"Judgment","description":"Court issues decision"}]'::jsonb,
ARRAY['All relevant documents', 'Previous correspondence', 'CNIC', 'Lawyer vakalatnama'],
ARRAY['High Court registry number'],
ARRAY['registrar@lhc.gov.pk'],
ARRAY['https://lhc.gov.pk'],
'Varies - few days to months', true, 1560, 89, 4.1, '2025-01-04'::date),

-- MORE PROPERTY & LAND
('Building Approval Plan Application', 'building-approval-plan', (SELECT id FROM categories WHERE slug = 'property-land' LIMIT 1),
'Get building plan approved from development authority before construction.',
'[{"number":1,"title":"Hire Architect","description":"Engage licensed architect for drawings"},{"number":2,"title":"Prepare Plans","description":"Architect prepares building plans"},{"number":3,"title":"Submit to Authority","description":"Apply to LDA/CDA/RDA/TMA"},{"number":4,"title":"Pay Fee","description":"Pay plan approval fee"},{"number":5,"title":"Scrutiny","description":"Authority reviews plan compliance"},{"number":6,"title":"Site Inspection","description":"Officer may visit site"},{"number":7,"title":"Approval","description":"Get approved plan with stamp"},{"number":8,"title":"Start Construction","description":"Begin building within validity period"}]'::jsonb,
ARRAY['Property documents', 'Architect drawings', 'Site plan', 'NOC from society', 'CNIC'],
ARRAY['LDA/CDA number'],
ARRAY['buildingcontrol@lda.gop.pk'],
ARRAY['https://lda.gop.pk'],
'15-30 working days', true, 3120, 189, 4.5, '2025-01-11'::date),

('Completion Certificate for Building', 'building-completion-certificate', (SELECT id FROM categories WHERE slug = 'property-land' LIMIT 1),
'Get completion certificate after finishing construction.',
'[{"number":1,"title":"Complete Construction","description":"Finish building as per approved plan"},{"number":2,"title":"Apply for Inspection","description":"Request completion inspection"},{"number":3,"title":"Pay Fee","description":"Pay completion certificate fee"},{"number":4,"title":"Site Inspection","description":"Building control officer inspects"},{"number":5,"title":"Verify Compliance","description":"Check if built as per plan"},{"number":6,"title":"Get Certificate","description":"Completion certificate issued"}]'::jsonb,
ARRAY['Approved building plan', 'Property documents', 'Construction photos', 'Utilities connected proof'],
ARRAY['LDA/CDA number'],
ARRAY['buildingcontrol@lda.gop.pk'],
ARRAY['https://lda.gop.pk'],
'7-15 working days', true, 1890, 112, 4.4, '2025-01-09'::date),

('Encroachment Complaint Filing', 'encroachment-complaint', (SELECT id FROM categories WHERE slug = 'property-land' LIMIT 1),
'Report illegal encroachment on your land or public property.',
'[{"number":1,"title":"Document Evidence","description":"Photos, videos of encroachment"},{"number":2,"title":"Verify Ownership","description":"Get your land records (Fard)"},{"number":3,"title":"File Complaint","description":"Submit to DC office or Development Authority"},{"number":4,"title":"Site Inspection","description":"Revenue officer visits site"},{"number":5,"title":"Notice to Encroacher","description":"Show cause notice issued"},{"number":6,"title":"Action Taken","description":"Encroachment removed by authorities"}]'::jsonb,
ARRAY['Land documents/Fard', 'Photos of encroachment', 'CNIC', 'Written complaint'],
ARRAY['DC office number', 'LDA number'],
ARRAY['dcoffice@punjab.gov.pk'],
ARRAY['https://citizenportal.gov.pk'],
'15-45 days for action', true, 2340, 145, 4.3, '2025-01-07'::date),

('Housing Society Verification', 'housing-society-verification', (SELECT id FROM categories WHERE slug = 'property-land' LIMIT 1),
'Verify if housing society is legally approved before investing.',
'[{"number":1,"title":"Check LDA List","description":"Visit LDA/CDA website for approved societies"},{"number":2,"title":"Verify NOC","description":"Ask society for NOC copy"},{"number":3,"title":"Physical Verification","description":"Visit LDA office to confirm"},{"number":4,"title":"Check Development","description":"Visit site to see actual progress"},{"number":5,"title":"Legal Advice","description":"Consult lawyer before investing"}]'::jsonb,
ARRAY['Society marketing material', 'NOC copy from society', 'Location details'],
ARRAY['LDA helpline'],
ARRAY['info@lda.gop.pk'],
ARRAY['https://lda.gop.pk/approved-societies'],
'Instant online check', true, 4560, 278, 4.6, '2025-01-05'::date),

-- ADDITIONAL MISC GUIDES
('Income Tax Return Filing Guide', 'income-tax-return-filing', (SELECT id FROM categories WHERE slug = 'legal-rights' LIMIT 1),
'Step-by-step guide to file income tax return in Pakistan.',
'[{"number":1,"title":"Get NTN","description":"Register on FBR IRIS for National Tax Number"},{"number":2,"title":"Gather Documents","description":"Salary slips, bank statements, property docs"},{"number":3,"title":"Calculate Tax","description":"Compute taxable income and tax liability"},{"number":4,"title":"Login IRIS","description":"Access FBR IRIS portal"},{"number":5,"title":"Fill Return Form","description":"Complete online return form"},{"number":6,"title":"Upload Documents","description":"Attach wealth statement docs"},{"number":7,"title":"Submit Return","description":"File return before deadline"},{"number":8,"title":"Pay Tax","description":"Pay any dues via ATL PSId"}]'::jsonb,
ARRAY['CNIC', 'Salary certificate', 'Bank statements', 'Property documents', 'Investment proofs'],
ARRAY['051-111-772-772'],
ARRAY['helpline@fbr.gov.pk'],
ARRAY['https://iris.fbr.gov.pk'],
'Must file by September 30', true, 5670, 345, 4.7, '2025-01-14'::date),

('Vehicle Import/Clearance Guide', 'vehicle-import-clearance', (SELECT id FROM categories WHERE slug = 'roads-transport' LIMIT 1),
'Import used or new vehicle from abroad through customs.',
'[{"number":1,"title":"Check Policy","description":"Verify current import policy from Customs"},{"number":2,"title":"Select Vehicle","description":"Choose vehicle within age limit"},{"number":3,"title":"Shipping","description":"Arrange shipping to Pakistan port"},{"number":4,"title":"Pay Duties","description":"Calculate and pay customs duties"},{"number":5,"title":"Customs Clearance","description":"Clear vehicle from Customs"},{"number":6,"title":"Registration","description":"Register with Excise department"}]'::jsonb,
ARRAY['Import documents', 'Passport', 'CNIC', 'Payment proof', 'Vehicle documents'],
ARRAY['051-9206600', 'Customs helpline'],
ARRAY['info@customs.gov.pk'],
ARRAY['https://customs.gov.pk'],
'15-30 days for clearance', true, 2340, 145, 4.4, '2025-01-12'::date),

('Police Verification Certificate', 'police-verification-certificate', (SELECT id FROM categories WHERE slug = 'legal-rights' LIMIT 1),
'Get character/police verification certificate for jobs/visa.',
'[{"number":1,"title":"Apply Online","description":"Submit on Punjab Police website"},{"number":2,"title":"Pay Fee","description":"Pay verification fee online"},{"number":3,"title":"Provide Details","description":"Submit all required information"},{"number":4,"title":"Wait for Processing","description":"Police verifies records"},{"number":5,"title":"Collect Certificate","description":"Get certificate from designated office"}]'::jsonb,
ARRAY['CNIC copy', 'Photos', 'Address proof', 'Purpose letter'],
ARRAY['042-99205256'],
ARRAY['verification@punjabpolice.gov.pk'],
ARRAY['https://punjabpolice.gov.pk/charactercertificate'],
'7-14 working days', true, 3890, 234, 4.5, '2025-01-10'::date),

('Arms License Application', 'arms-license-application', (SELECT id FROM categories WHERE slug = 'legal-rights' LIMIT 1),
'Apply for non-prohibited bore weapon license.',
'[{"number":1,"title":"Check Eligibility","description":"Age 21+, no criminal record"},{"number":2,"title":"Apply to DC Office","description":"Submit application with documents"},{"number":3,"title":"Pay Fee","description":"Pay license fee"},{"number":4,"title":"Police Verification","description":"SHO verifies your background"},{"number":5,"title":"DC Approval","description":"Deputy Commissioner approves"},{"number":6,"title":"Get License","description":"Collect arms license"}]'::jsonb,
ARRAY['CNIC', 'Domicile', 'Character certificate', 'Photos', 'Reason for license'],
ARRAY['DC office number'],
ARRAY['dcoffice@punjab.gov.pk'],
ARRAY['https://punjab.gov.pk'],
'30-90 days', true, 1780, 98, 4.2, '2025-01-08'::date),

('Disability Certificate/Card', 'disability-certificate-card', (SELECT id FROM categories WHERE slug = 'social-causes' LIMIT 1),
'Get disability certificate for special benefits and quota.',
'[{"number":1,"title":"Medical Assessment","description":"Get disability assessed by Medical Board"},{"number":2,"title":"Apply at Social Welfare","description":"Submit application at district SW office"},{"number":3,"title":"Verification","description":"Officer verifies disability"},{"number":4,"title":"Get Certificate","description":"Disability certificate issued"},{"number":5,"title":"NADRA Update","description":"Update CNIC with disability status"}]'::jsonb,
ARRAY['Medical reports', 'CNIC', 'Photos', 'Hospital certificate'],
ARRAY['042-99205267'],
ARRAY['disability@socialwelfare.punjab.gov.pk'],
ARRAY['https://socialwelfare.punjab.gov.pk'],
'7-15 working days', true, 2120, 134, 4.6, '2025-01-06'::date),

('Zakat Application for Deserving', 'zakat-application-deserving', (SELECT id FROM categories WHERE slug = 'social-causes' LIMIT 1),
'Apply for Zakat assistance if you are eligible.',
'[{"number":1,"title":"Check Eligibility","description":"Must be Mustahiq (deserving) as per Zakat law"},{"number":2,"title":"Visit Zakat Committee","description":"Go to local Zakat committee"},{"number":3,"title":"Submit Application","description":"Apply for assistance"},{"number":4,"title":"Verification","description":"Committee verifies need"},{"number":5,"title":"Approval","description":"Zakat disbursed if approved"}]'::jsonb,
ARRAY['CNIC', 'Income proof', 'Recommendation from local'],
ARRAY['042-99205215'],
ARRAY['zakat@punjab.gov.pk'],
ARRAY['N/A'],
'15-30 days', true, 1560, 89, 4.4, '2025-01-04'::date),

('Pension Application Government Employees', 'pension-application-government', (SELECT id FROM categories WHERE slug = 'social-causes' LIMIT 1),
'Apply for pension after retirement from government service.',
'[{"number":1,"title":"6 Months Before Retirement","description":"Start process 6 months early"},{"number":2,"title":"Prepare PPO","description":"Get Pension Payment Order prepared"},{"number":3,"title":"Submit Documents","description":"Service record, CNIC, bank details"},{"number":4,"title":"Verification","description":"AG office verifies service"},{"number":5,"title":"PPO Issued","description":"Receive your PPO"},{"number":6,"title":"First Pension","description":"Pension credited to bank"}]'::jsonb,
ARRAY['Service book', 'Last pay certificate', 'CNIC', 'Bank account details'],
ARRAY['AG office number'],
ARRAY['pension@agpunjab.gov.pk'],
ARRAY['https://agpunjab.gov.pk'],
'2-3 months if timely', true, 2890, 167, 4.5, '2025-01-02'::date),

('Inheritance Certificate (Warasat Nama)', 'inheritance-certificate-warasat', (SELECT id FROM categories WHERE slug = 'property-land' LIMIT 1),
'Get legal heir certificate for inheritance matters.',
'[{"number":1,"title":"Gather Heirs","description":"Identify all legal heirs"},{"number":2,"title":"Apply to Court","description":"File succession case in civil court"},{"number":3,"title":"Submit Documents","description":"Death certificate, family tree, CNIC"},{"number":4,"title":"Public Notice","description":"Court publishes notice for objections"},{"number":5,"title":"Hearing","description":"All heirs appear in court"},{"number":6,"title":"Get Certificate","description":"Succession certificate issued"}]'::jsonb,
ARRAY['Death certificate', 'CNIC of all heirs', 'Family tree', 'Property documents'],
ARRAY['District courts number'],
ARRAY['N/A'],
ARRAY['N/A'],
'30-90 days', true, 3450, 212, 4.4, '2025-01-01'::date)

ON CONFLICT (slug) DO UPDATE SET 
  views_count = EXCLUDED.views_count,
  upvotes_count = EXCLUDED.upvotes_count,
  updated_at = now();

