-- Seed Guides SQL Script
-- Run this in Supabase SQL Editor: https://supabase.com/dashboard/project/tstzrjdxzvepdiaxmllf/sql

-- First, let's get the category IDs and insert the guides
DO $$
DECLARE
    roads_cat_id UUID;
    water_cat_id UUID;
BEGIN
    -- Get category IDs
    SELECT id INTO roads_cat_id FROM categories WHERE name = 'Roads & Transport' LIMIT 1;
    SELECT id INTO water_cat_id FROM categories WHERE name = 'Sewerage & Water' LIMIT 1;

    -- If categories don't exist, create them
    IF roads_cat_id IS NULL THEN
        INSERT INTO categories (name, slug, description, icon)
        VALUES ('Roads & Transport', 'roads-transport', 'Road maintenance, traffic, and public transport services', 'road')
        RETURNING id INTO roads_cat_id;
    END IF;

    IF water_cat_id IS NULL THEN
        INSERT INTO categories (name, slug, description, icon)
        VALUES ('Sewerage & Water', 'sewerage-water', 'Water supply, sewerage, and drainage services', 'droplet')
        RETURNING id INTO water_cat_id;
    END IF;

    -- Insert Roads & Transport guides
    INSERT INTO guides (title, slug, category_id, problem_explanation, steps, required_documents, timeline_expectation, estimated_cost, pro_tips, is_published, views_count, upvotes_count)
    VALUES 
    ('How to Report Pothole to City Authority', 'how-to-report-pothole-to-city-authority', roads_cat_id, 'Complete guide on How to Report Pothole to City Authority. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 150, 25),
    
    ('Traffic Challan Payment Online Punjab', 'traffic-challan-payment-online-punjab', roads_cat_id, 'Complete guide on Traffic Challan Payment Online Punjab. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 280, 45),
    
    ('Traffic Challan Payment Online Sindh', 'traffic-challan-payment-online-sindh', roads_cat_id, 'Complete guide on Traffic Challan Payment Online Sindh. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 220, 38),
    
    ('Driving License Application New', 'driving-license-application-new', roads_cat_id, 'Complete guide on Driving License Application New. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 450, 78),
    
    ('Driving License Renewal', 'driving-license-renewal', roads_cat_id, 'Complete guide on Driving License Renewal. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 380, 62),
    
    ('International Driving Permit', 'international-driving-permit', roads_cat_id, 'Complete guide on International Driving Permit. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 190, 32),
    
    ('Vehicle Registration New Car', 'vehicle-registration-new-car', roads_cat_id, 'Complete guide on Vehicle Registration New Car. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 320, 55),
    
    ('Vehicle Registration Transfer', 'vehicle-registration-transfer', roads_cat_id, 'Complete guide on Vehicle Registration Transfer. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 290, 48),
    
    ('Vehicle Token Tax Payment', 'vehicle-token-tax-payment', roads_cat_id, 'Complete guide on Vehicle Token Tax Payment. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 410, 68),
    
    ('Motorway Helpline Usage', 'motorway-helpline-usage', roads_cat_id, 'Complete guide on Motorway Helpline Usage. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 175, 28),
    
    ('Metro Bus Card Lahore', 'metro-bus-card-lahore', roads_cat_id, 'Complete guide on Metro Bus Card Lahore. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 340, 58),
    
    ('Metro Bus Card Islamabad', 'metro-bus-card-islamabad', roads_cat_id, 'Complete guide on Metro Bus Card Islamabad. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 295, 49),
    
    ('Orange Line Train Lahore', 'orange-line-train-lahore', roads_cat_id, 'Complete guide on Orange Line Train Lahore. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 365, 61),
    
    ('Public Transport Complaint', 'public-transport-complaint', roads_cat_id, 'Complete guide on Public Transport Complaint. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 125, 21),
    
    ('Road Damage Report', 'road-damage-report', roads_cat_id, 'Complete guide on Road Damage Report. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 185, 30),
    
    ('Traffic Signal Fault Report', 'traffic-signal-fault-report', roads_cat_id, 'Complete guide on Traffic Signal Fault Report. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 95, 15),
    
    ('Parking Challan Appeal', 'parking-challan-appeal', roads_cat_id, 'Complete guide on Parking Challan Appeal. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 140, 23),
    
    ('Vehicle Fitness Certificate', 'vehicle-fitness-certificate', roads_cat_id, 'Complete guide on Vehicle Fitness Certificate. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 210, 35),
    
    ('Route Permit Application', 'route-permit-application', roads_cat_id, 'Complete guide on Route Permit Application. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 130, 22),
    
    ('Heavy Vehicle License', 'heavy-vehicle-license', roads_cat_id, 'Complete guide on Heavy Vehicle License. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 165, 27),
    
    ('PSV Badge Application', 'psv-badge-application', roads_cat_id, 'Complete guide on PSV Badge Application. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 88, 14),
    
    ('Careem Uber Driver Registration', 'careem-uber-driver-registration', roads_cat_id, 'Complete guide on Careem Uber Driver Registration. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 420, 72),
    
    ('E-Bike Registration', 'e-bike-registration', roads_cat_id, 'Complete guide on E-Bike Registration. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 255, 42),
    
    ('Vehicle Auction Participation', 'vehicle-auction-participation', roads_cat_id, 'Complete guide on Vehicle Auction Participation. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 178, 29),
    
    ('Hit and Run Report', 'hit-and-run-report', roads_cat_id, 'Complete guide on Hit and Run Report. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 67, 11)
    ON CONFLICT (slug) DO UPDATE SET 
        title = EXCLUDED.title,
        problem_explanation = EXCLUDED.problem_explanation,
        is_published = EXCLUDED.is_published;

    -- Insert Sewerage & Water guides
    INSERT INTO guides (title, slug, category_id, problem_explanation, steps, required_documents, timeline_expectation, estimated_cost, pro_tips, is_published, views_count, upvotes_count)
    VALUES 
    ('WASA New Connection Lahore', 'wasa-new-connection-lahore', water_cat_id, 'Complete guide on WASA New Connection Lahore. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 385, 64),
    
    ('WASA New Connection Faisalabad', 'wasa-new-connection-faisalabad', water_cat_id, 'Complete guide on WASA New Connection Faisalabad. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 245, 40),
    
    ('WASA Complaint Registration', 'wasa-complaint-registration', water_cat_id, 'Complete guide on WASA Complaint Registration. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 310, 52),
    
    ('Water Supply Disruption Report', 'water-supply-disruption-report', water_cat_id, 'Complete guide on Water Supply Disruption Report. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 198, 33),
    
    ('Sewerage Blockage Complaint', 'sewerage-blockage-complaint', water_cat_id, 'Complete guide on Sewerage Blockage Complaint. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 425, 71),
    
    ('Water Bill Payment Online', 'water-bill-payment-online', water_cat_id, 'Complete guide on Water Bill Payment Online. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 480, 82),
    
    ('Water Meter Installation', 'water-meter-installation', water_cat_id, 'Complete guide on Water Meter Installation. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 215, 36),
    
    ('Water Tanker Request', 'water-tanker-request', water_cat_id, 'Complete guide on Water Tanker Request. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 155, 26),
    
    ('Boring Tubewell Permission', 'boring-tubewell-permission', water_cat_id, 'Complete guide on Boring Tubewell Permission. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 112, 18),
    
    ('Water Quality Test Request', 'water-quality-test-request', water_cat_id, 'Complete guide on Water Quality Test Request. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 98, 16),
    
    ('PHED Complaint Punjab', 'phed-complaint-punjab', water_cat_id, 'Complete guide on PHED Complaint Punjab. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 142, 24),
    
    ('KWSB Complaint Karachi', 'kwsb-complaint-karachi', water_cat_id, 'Complete guide on KWSB Complaint Karachi. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 275, 46),
    
    ('Illegal Water Connection Report', 'illegal-water-connection-report', water_cat_id, 'Complete guide on Illegal Water Connection Report. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 78, 13),
    
    ('Water Theft Report', 'water-theft-report', water_cat_id, 'Complete guide on Water Theft Report. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 65, 10),
    
    ('Rainwater Drainage Issue', 'rainwater-drainage-issue', water_cat_id, 'Complete guide on Rainwater Drainage Issue. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 188, 31),
    
    ('Flood Damage Report', 'flood-damage-report', water_cat_id, 'Complete guide on Flood Damage Report. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 235, 39),
    
    ('Water Conservation Tips', 'water-conservation-tips', water_cat_id, 'Complete guide on Water Conservation Tips. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 320, 54),
    
    ('Sewerage Line Extension Request', 'sewerage-line-extension-request', water_cat_id, 'Complete guide on Sewerage Line Extension Request. This guide explains the process, requirements, and steps to resolve this issue or avail this service in Pakistan.', '[{"number": 1, "title": "Preparation", "description": "Gather all necessary documents such as CNIC, proof of residence, and any previous records."}, {"number": 2, "title": "Visit Office / Online Portal", "description": "Visit the relevant department office or their official website/app."}, {"number": 3, "title": "Submit Application", "description": "Fill out the application form carefully and attach required documents."}, {"number": 4, "title": "Pay Fees", "description": "Pay any applicable fees via bank challan or digital payment methods."}, {"number": 5, "title": "Follow Up", "description": "Track your application status and wait for processing."}]', '["Original CNIC", "Copies of CNIC", "Passport size photos", "Application Form"]', '3-7 working days', 'Varies (Check official rates)', 'Always keep photocopies of your submitted documents. Visit offices early in the morning to avoid queues.', true, 108, 17)
    ON CONFLICT (slug) DO UPDATE SET 
        title = EXCLUDED.title,
        problem_explanation = EXCLUDED.problem_explanation,
        is_published = EXCLUDED.is_published;

    RAISE NOTICE '✅ Successfully seeded 43 guides (25 Roads & Transport, 18 Sewerage & Water)';
END $$;
